### ISSUE TITLE
Crash when blueprint tries to create an instance of the abstract class "gtk widget"

### ISSUE THREAD

**Issue by mijorus** [sonnyp/Workbench#165]
```
(workbench-vala-previewer:38): Adwaita-WARNING **: 20:30:23.189: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

(re.sonny.Workbench:4): GLib-GObject-ERROR **: 20:30:23.327: cannot create instance of abstract (non-instantiatable) type 'GtkWidget'
```

This is the file I want to edit:
```
using Gtk 4.0;
using Adw 1;

Widget {
    
}
```

I am guessing that this syntax is wrong 😅

**Comment by sonnyp** [comment]
Thanks for reporting.

> I am guessing that this syntax is wrong sweat_smile

Yes but as a tool for beginners/prototyping Workbench shouldn't crash with cryptic error messages :smile: 

 Unfortunately, the error says it all – it's not possible to preview (or create) `Gtk.Widget` directly because it is an abstract value.

Usually in a UI definition you would use it for a composite template like

```
using Gtk 4.0;
using Adw 1;

template Widget {
    
}
```

Workbench won't crash there (I think I implemented a workaround, but I should do the same for non-template) but it's still not preview-able directly.

I'd recommend extending `Box` or `Button` or whatever instead for now.

**Comment by sonnyp** [comment]
```
rm ~/.var/app/re.sonny.Workbench/data/re.sonny.Workbench/state.blp
```

should do the trick if the cause of the crash is the Blueprint file

I've been wanting to implement a way to prevent this crash loop.

I will leave this open for 

1. Prevent the crash in the first place
2. Detect and recover from crash

**Comment by sonnyp** [comment]
> Prevent the crash in the first place

Fixes in https://github.com/sonnyp/Workbench/commit/cc7279e82aab7c06909ea966ccbdddafe1d353f2

> Detect and recover from crash

https://github.com/sonnyp/Workbench/issues/170
