### ISSUE TITLE
Support other languages

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Workbench#17]
It should be possible to support other languages than JavaScript.

We will have to change the preview to be out of process thought.

Could be an external window or simply use broadway GTK backend https://docs.gtk.org/gtk4/broadway.html

**Comment by lw64** [comment]
It would be nice to have support for Vala. (https://gitlab.gnome.org/GNOME/vala/)

This would even work without an external process.

First the source needs to be compiled into a library and then also GIR metadata generated. (by the Vala compiler). After that this library can be loaded from Workbench and can be used with js, because of the gobject-introspection.

Either there would be a vala function to invoke from workbench to start the program, or the vala code could be used from the js tab.

The only thing I don't know is, if the library could be also unloaded after stopping the program. Because after multiple times, the memory footprint could grow a bit.

**Comment by sonnyp** [comment]
Right, but it sounds like using an external process would be so much easier to implement and maintain.

I'm wondering if rendering in a separate window would be such a big deal. WDYT ?

The other benefit is that we could sandbox that process for untrusted input. We've been toying with using Workbench for running examples from the GJS website.

Could also allow running on a remote device (phone).

If we went with in-process – I would probably rewrite Workbench in C for better interop with the ecosystem. 

> The only thing I don't know is, if the library could be also unloaded after stopping the program. Because after multiple times, the memory footprint could grow a bit.

That's also the case with the current implementation, we can't unload the JavaScript but I doubt it would really be a problem.

**Comment by lw64** [comment]
> I'm wondering if previewing in a separate window would be such a big deal. WDYT ?

Actually I think that having a separate window would be better. (It also looks better than having it embedded.)

> The other benefit is that we could sandbox that process for untrusted input. We've been toying with using Workbench for running examples from the GJS website.

That would be really good, because then you wouldn't need a special "dev-environment". Build everything with the flatpak Sdk and run it in the flatpak runtime. The only disadvantage would be to build always a new flatpak package, which is sometimes slow. But I think you can also execute programs in a flatpak runtime without generating a flarpak package before. GNOME-Builder was doing that until it broke somehow, I think.

> Could also allow running on a remote device (phone).

I think that isn't in the scope of workbench anymore. That can be handled by Builder.

It would be interesting though to run workbench at all on mobile.

**Comment by sonnyp** [comment]
> Actually I think that having a separate window would be better. (It also looks better than having it embedded.)

Can you expand on why you would it would be better?

Yet an other benefit I just thought of is allowing to render `<object class="GtkWindow/>` without too much hacks.

**Comment by lw64** [comment]
A separate window just looks more like what you would expect from an "app". You want to show around maybe, what you have achieved, in which case the ui of workbench surrounding it wouldn't be wanted. You also can have your own headerbar, which means to have a "GNOME/Adwaita styled" app.

A "Export to Flatpak bundle" would be then also reasonable to have.

**Comment by sonnyp** [comment]
@ADBeveridge agree - both would be ideal and a good place to start

I have created a follow up https://github.com/sonnyp/Workbench/issues/34 - happy to hear your thoughts @lw64 and @ADBeveridge

**Comment by lw64** [comment]
Because I have absolutely no experience at all with javascript, I could make a small in-project vala library that takes the textbuffers, root output-widget and has a run method. that would only need to be connected ui-wise from js then.

Or this can be generalized and a plugin interface could be added to workbench.

**Comment by lw64** [comment]
Also if multiple language will be supported, there should be also links to the documentation of these languages. How could that look well organized. Or maybe the links are exchanged when you switch the language in workbench?

**Comment by sonnyp** [comment]
Let's start with a PoC first and worry about the UI later :+1: 

> I could make a small in-project vala library that takes the textbuffers, root output-widget and has a run method. that would only need to be connected ui-wise from js then.

What about toolchain and compiling? I think I'm missing something.
We're talking about allowing users to write Vala in `Code` and `Run` it ?

**Comment by lw64** [comment]
Yes. the toolchain, compilation and execution would be all handled by this library.

**Comment by lw64** [comment]
When I switch between the languages, should the buffer of the code view or even the XML and css view be exchanged too?

Also in the library the demos would be categorised for languages and how should demos handled that exist in both languages?

**Comment by sonnyp** [comment]
I already have code to support that, please give me a bit of time to ship it and we can build Vala support on top of that.

In the meantime feel free to hack something quick and dirty for PoC vala support.

-- 
  Sonny Piers
  ***@***.***

**Comment by lw64** [comment]
Oh. Ok. I think I will wait for that then. That is the most important part and most of the work, I think. Some input from my side:

CSS and XML can be live previewed with it out of process with some IPC communication. Maybe a dbus function that I indicates reloadinging it from some files. Code, CSS, and XML are of course stored as temporary files. Also the code formatting of the sourceview needs to be changed on switching.

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Workbench/issues/77
