### ISSUE TITLE
Hide unrelated logs

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Workbench#78]
Let's make a custom logger and filter out stuff that might confuse or spam users like those Gdk-CRITICAL

see

* https://gitlab.gnome.org/GNOME/gtk/-/issues/4344
* https://ar.al/2021/10/15/how-to-disable-gtk-message-warnings-in-your-app/

![image](https://user-images.githubusercontent.com/19673/169364521-5fe43d35-7b8c-4390-9610-3372dbb24340.png)

![image](https://user-images.githubusercontent.com/19673/169645714-75441bf1-a93b-48fc-bd57-86246f05e17b.png)

You can ignore the first line - it's only an issue on flatpak development

**Comment by sonnyp** [comment]
https://ar.al/2021/10/15/how-to-disable-gtk-message-warnings-in-your-app/

**Comment by lw64** [comment]
It would be best to just not show the unneeded error messages in the console. They can be still very useful in the logs, or when you start the app from the terminal to debug.

Or only give the right messages to the console. That would work for example by piping the previewer output to the console, and nothing else. Especially because also the user can mess up with the code and generate criticals, that would be helpful and important to fix the code.

**Comment by sonnyp** [comment]
> It would be best to just not show the unneeded error messages in the console. 

That's what this issue is abou

>  filter out stuff that might confuse or spam users like those Gdk-CRITICAL

**Comment by lw64** [comment]
I mean instead of disabling them alltogether.

**Comment by sonnyp** [comment]
Unfortunately, I couldn't use https://docs.gtk.org/glib/func.log_set_writer_func.html because of https://gitlab.gnome.org/GNOME/gjs/-/issues/481

For now it just filters out what it can and what is the most urgent - in the future we can consider bootstrapping gjs from a C entry file - similar to Polari https://gitlab.gnome.org/GNOME/polari/-/blob/main/src/polari.c and use log_set_writer_func from C
